services:
  redis:
    image: redis:7
    container_name: colearn-redis-cache
    ports:
      - "6379:6379"
    volumes:
      - colearn-redis-data:/data

  mongodb:
    image: mongo:7
    container_name: colearn-mongodb
    ports:
      - "27017:27017"
    volumes:
      - colearn-mongodb-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: colearn

volumes:
  colearn-redis-data:
  colearn-mongodb-data:
